apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
  name: myiis-ingress
spec:
  rules:
    - host: {{ .Values.apphost }}
      http:
        paths:
          - path: /
            backend:
              serviceName: myiis-service
              servicePort: 80
  tls:
    - hosts:
      - {{ .Values.apphost }}
      secretName: tomaskubicain