apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
  name: myiis-ingress
spec:
  rules:
    - host: {{ .Values.apphost }}
      http:
        paths:
          - path: /
            backend:
              serviceName: myiis-service
              servicePort: 80
