apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: myweb
spec:
  provider: istio
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myweb
  progressDeadlineSeconds: 60
  service:
    port: 80
    targetPort: 80
  canaryAnalysis:
    interval: 10s
    threshold: 10
    iterations: 12
    match:
      - headers:
          tester:
            exact: "true"
      - headers:
          cookie:
            exact: "canary"
    metrics:
    - name: request-success-rate
      threshold: 99
      interval: 1m