apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: ab-nginx
spec:
  provider: nginx
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ab-nginx
  ingressRef:
    apiVersion: extensions/v1beta1
    kind: Ingress
    name: ab-nginx
  progressDeadlineSeconds: 60
  service:
    port: 80
    targetPort: 8080
  analysis:
    interval: 20s
    threshold: 10
    maxWeight: 50
    stepWeight: 10
    match:
    # curl -H 'X-Canary: insider' http://app.example.com
    - headers:
        x-canary:
          exact: "insider"
    # curl -b 'canary=always' http://app.example.com
    - headers:
        cookie:
          exact: "canary"
    metrics:
    - name: "latency"
      templateRef:
        name: latency
      thresholdRange:
        max: 0.5
      interval: 10s