apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo-ingress
spec:
  provider: nginx
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo-ingress
  ingressRef:
    apiVersion: extensions/v1beta1
    kind: Ingress
    name: podinfo-ingress-ingress
  progressDeadlineSeconds: 60
  service:
    port: 80
    targetPort: 8080
  analysis:
    interval: 10s
    threshold: 10
    maxWeight: 50
    stepWeight: 5
    metrics:
    - name: request-success-rate
      threshold: 99
      interval: 1m
    webhooks:
      - name: load-test
        url: http://flagger-loadtester/
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://podinfo-ingress-canary/"