apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: ab-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
  name: ab-nginx
spec:
  rules:
    - host: "{{ .Values.ingress.ab.host }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: ab-nginx
              servicePort: 80