kind: Service
apiVersion: v1
metadata:
  name: myweb-service-v1
  labels:
    app: myweb
    version: v1
spec:
  selector:
    app: myweb
    version: v1
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: myweb-service-v2
  labels:
    app: myweb
    version: v2
spec:
  selector:
    app: myweb
    version: v2
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: myweb-service
spec:
  service: myweb-service
  backends:
  - service: myweb-service-v1
    weight: 900m
  - service: myweb-service-v2
    weight: 100m