apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-retry
  labels:
    app: {{ template "name" . }}-retry
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: {{ template "fullname" . }}-retry
  selector:
    app: {{ template "name" . }}-retry
    release: {{ .Release.Name }}
