apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
  name: ingress-to-nginx
  namespace: ingress
spec:
  rules:
  - host: linkerd.i.cloud.tomaskubica.in
    http:
      paths:
      - backend:
          serviceName: ingress-nginx-nginx-ingress-controller
          servicePort: 80
        path: /
  - host: canary.nginx.i.cloud.tomaskubica.in
    http:
      paths:
      - backend:
          serviceName: ingress-nginx-nginx-ingress-controller
          servicePort: 80
        path: /
  - host: ab.nginx.i.cloud.tomaskubica.in
    http:
      paths:
      - backend:
          serviceName: ingress-nginx-nginx-ingress-controller
          servicePort: 80
        path: /
  tls:
    - hosts:
      - linkerd.i.cloud.tomaskubica.in
      - canary.nginx.i.cloud.tomaskubica.in
      - ab.nginx.i.cloud.tomaskubica.in
      secretName: tomaskubicain