apiVersion: v1
kind: Secret
metadata:
  name: grafana-login
  namespace: grafana
type: Opaque
data:
  admin-user: {{ .Values.username | b64enc | quote }}
  admin-password: {{ .Values.password | b64enc | quote }}=