apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: secrets-reader
spec:
  type: 0
  resourceID: {{ .Values.secretsReader.resourceId }}
  clientID: {{ .Values.secretsReader.clientId }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: secrets-reader-binding
spec: 
  azureIdentity: secrets-reader
  selector: secrets-reader