apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: secrets-reader
  annotations:
    aadpodidentity.k8s.io/Behavior: namespaced
spec:
  type: 0
  ResourceID: {{ .Values.secretsReader.resourceId }}
  ClientID: {{ .Values.secretsReader.clientId }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: secrets-reader-binding
spec: 
  AzureIdentity: secrets-reader
  Selector: secrets-reader