apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: keda
spec:
  type: 0
  resourceID: {{ .Values.keda.resourceId }}
  clientID: {{ .Values.keda.clientId }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: keda-binding
spec: 
  azureIdentity: keda
  selector: keda