replicaCount: 2
ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: azure/application-gateway
  hosts: 
  - canary.nginx.linkerd.cloud.tomaskubica.in
ui:
  color: #34577c
  message: 'Ahoj z V1'
linkerd:
  profile:
    enabled: true