replicaCount: 2
ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: azure/application-gateway
  hosts: 
  - podinfo.ingress.nginx.cloud.tomaskubica.in
ui:
  color: #34577b
  message: 'Ahoj z V1'
linkerd:
  profile:
    enabled: true