name: Deploy

on:
  push:
    paths: 
      - "demo/**"
      - ".github/workflows/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo files
      uses: actions/checkout@v1
     
    - name: Install Terraform
      uses: little-core-labs/install-terraform@v1.0.0
      with:
        version: 0.12.21

    - name: Init Terraform
      working-directory: ./demo
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
        ARM_CLIENT_ID: ${{ secrets.client_id }}
        ARM_CLIENT_SECRET: ${{ secrets.client_secret }}
        ARM_TENANT_ID: ${{ secrets.tenant_id }}
      run: terraform init
    
    - name: Deploy Azure infrastructure
      working-directory: ./demo
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
        ARM_CLIENT_ID: ${{ secrets.client_id }}
        ARM_CLIENT_SECRET: ${{ secrets.client_secret }}
        ARM_TENANT_ID: ${{ secrets.tenant_id }}  
        TF_VAR_subscription_id: ${{ secrets.subscription_id }}
        TF_VAR_client_id: ${{ secrets.client_id }}
        TF_VAR_client_secret: ${{ secrets.client_secret }}
        TF_VAR_tenant_id: ${{ secrets.tenant_id }}
        TF_VAR_psql_password: ${{ secrets.psql_password }} 
        TF_VAR_vm_password: ${{ secrets.vm_password }} 
        TF_VAR_client_app_id: ${{ secrets.client_app_id }}
        TF_VAR_server_app_id: ${{ secrets.server_app_id }}
        TF_VAR_server_app_secret: ${{ secrets.server_app_secret }}
        TF_VAR_tenant_app_id: ${{ secrets.tenant_app_id }}
      run: terraform apply -auto-approve

    - name: Store Kubernetes config
      working-directory: ./demo
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
        ARM_CLIENT_ID: ${{ secrets.client_id }}
        ARM_CLIENT_SECRET: ${{ secrets.client_secret }}
        ARM_TENANT_ID: ${{ secrets.tenant_id }}
      run: echo "$(terraform output kube_admin_config)" > ./kube_config

    - name: Install Helm 3
      uses: Azure/setup-helm@v1
      with:
        version: v3.1.1

    - name: Prepare SDK auth file
      working-directory: ./demo
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
        ARM_CLIENT_ID: ${{ secrets.client_id }}
        ARM_CLIENT_SECRET: ${{ secrets.client_secret }}
        ARM_TENANT_ID: ${{ secrets.tenant_id }}
      run: |
        sed -i "s/<azure_aubscription_id>/$ARM_SUBSCRIPTION_ID/g" sdk-auth.json
        sed -i "s/<application_id>/$ARM_CLIENT_ID/g" sdk-auth.json
        sed -i "s/<application_secret>/$ARM_CLIENT_SECRET/g" sdk-auth.json
        sed -i "s/<tenant_id>/$ARM_TENANT_ID/g" sdk-auth.json

    - name: Deploy cluster base configuration
      working-directory: ./demo
      env:
        KUBECONFIG: "./kube_config"
      run: |
        ls ./helm
        ls ./helm/cluster
        helm upgrade -i baseconfig ./helm/cluster \
          --set upn=admin@tomaskubicaoffice.onmicrosoft.com

    - name: Deploy Ingress controller for Azure App Gw
      env:
        KUBECONFIG: "./kube_config"
        ARM_SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
      run: |
        helm repo add application-gateway-kubernetes-ingress https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/
        helm repo update
        helm upgrade -i ingress application-gateway-kubernetes-ingress/ingress-azure \
          --set appgw.name=$(terraform output appgw_name) \
          --set appgw.resourceGroup=$(terraform output resource_group) \
          --set appgw.subscriptionId=$ARM_SUBSCRIPTION_ID \
          --set appgw.usePrivateIP=False \
          --set kubernetes.watchNamespace="" \
          --set armAuth.type=servicePrincipal \
          --set armAuth.secretJSON=$(cat sdk-auth.json | base64 -w0) \
          --set rbac.enabled=true