kind: Service
apiVersion: v1
metadata:
  name: dapr-localforwarder
  labels:
    app: dapr-localforwarder
spec:
  selector:
    app: dapr-localforwarder
  ports:
  - protocol: TCP
    port: 55678
    targetPort: 55678
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-localforwarder
  labels:
    app: dapr-localforwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-localforwarder
  template:
    metadata:
      labels:
        app: dapr-localforwarder
    spec:
      containers:
      - name: dapr-localforwarder
        image: docker.io/daprio/dapr-localforwarder:latest
        ports:
        - containerPort: 55678
        imagePullPolicy: Always
        env:
          - name: APPINSIGHTS_INSTRUMENTATIONKEY
            value: {{ .Values.appin_key }}
          - name: APPINSIGHTS_LIVEMETRICSSTREAMAUTHENTICATIONAPIKEY
            value: null