apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
spec:
  type: secretstores.azure.keyvault
  metadata:
    - name: vaultName
      value: {{ .Values.keyVault.name }}
    - name: spnClientId
      value: {{ .Values.keyVault.readerClientId }}