apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: binding-blob
spec:
  type: bindings.azure.blobstorage
  metadata:
  - name: storageAccount
    value: {{ .Values.blob.storageAccount }}
  - name: storageAccessKey
    secretKeyRef:
      name: blob-key
  - name: container
    value: {{ .Values.blob.container }}
auth:
  secretStore: azurekeyvault