apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mystate
spec:
  type: state.azure.cosmosdb
  metadata:
  - name: url
    value: {{ .Values.cosmos.host }}
  - name: database
    value: {{ .Values.cosmos.db }}
  - name: collection
    value: {{ .Values.cosmos.col }}
  - name: masterKey
    secretKeyRef:
      name: cosmos-key
auth:
  secretStore: azurekeyvault