apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nodeb
spec:
  selector:
    matchLabels:
      app: nodeb
  serviceName: nodeb
  replicas: 1
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "nodeb"
      labels:
        app: nodeb
        aadpodidbinding: secrets-reader
    spec:
      containers:
      - name: container
        image: "{{ .Values.appnodes.image.repository }}:{{ .Values.appnodes.image.tag | toString }}"
        resources:
          requests:
            cpu: 10m
            memory: 32M
          limits:
            cpu: 100M
            memory: 128M
