apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: subscribeeventhub
spec:
  selector:
    matchLabels:
      app: subscribeeventhub
  replicas: 1
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "subscribeeventhub"
        dapr.io/port: "5000"
      labels:
        app: subscribeeventhub
    spec:
      containers:
      - name: container
        image: "{{ .Values.appnodes.image.repository }}:{{ .Values.appnodes.image.tag | toString }}"
        command: ["python"]
        args: ["/home/user/binding.py"]
        ports:
          - containerPort: 5000
        resources:
          requests:
            cpu: 10m
            memory: 32M
          limits:
            cpu: 100M
            memory: 128M
